package Test;

public class Payload {
	public static String AddPlace() {
		return "{\r\n"
				+ "    \"location\": {\r\n"
				+ "        \"lat\": -37.383494,\r\n"
				+ "        \"lng\": 33.427362\r\n"
				+ "    },\r\n"
				+ "    \"accuracy\": 50,\r\n"
				+ "    \"name\": \"raghu house\",\r\n"
				+ "    \"phone_number\": \"(+91) 983 893 3937\",\r\n"
				+ "    \"address\": \"29, jhansi, cohen 09\",\r\n"
				+ "    \"types\": [\r\n"
				+ "        \"shoe park\",\r\n"
				+ "        \"shop\"\r\n"
				+ "    ],\r\n"
				+ "    \"website\": \"http://google.com\",\r\n"
				+ "    \"language\": \"French-IN\"\r\n"
				+ "}";
	}
	public static String addBook(String isbnno,String aislno) {
		String payLoad= "{\r\n"
				+ "    \"name\": \"Learn Appium Automation with Java\",\r\n"
				+ "    \"isbn\": \""+isbnno+"\",\r\n"
				+ "    \"aisle\": \""+aislno+"\",\r\n"
				+ "    \"author\": \"John foe\"\r\n"
				+ "}";
		return payLoad ;
	}
	public static String deleteBook(String id) {
		String payLoad= "{\r\n"
				+ " \r\n"
				+ "\"ID\" : \""+id+"\"\r\n"
				+ " \r\n"
				+ "} \r\n"
				+ "";
		return payLoad ;
	}
	public static String coursePrice() {
		return "{\r\n"
				+ "\r\n"
				+ "\"dashboard\": {\r\n"
				+ "\r\n"
				+ "\"purchaseAmount\": 910,\r\n"
				+ "\r\n"
				+ "\"website\": \"rahulshettyacademy.com\"\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "\"courses\": [\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"Selenium Python\",\r\n"
				+ "\r\n"
				+ "\"price\": 50,\r\n"
				+ "\r\n"
				+ "\"copies\": 6\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"Cypress\",\r\n"
				+ "\r\n"
				+ "\"price\": 40,\r\n"
				+ "\r\n"
				+ "\"copies\": 4\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"RPA\",\r\n"
				+ "\r\n"
				+ "\"price\": 45,\r\n"
				+ "\r\n"
				+ "\"copies\": 10\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "]\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "";
	}
	public static String createUpdate() {
	return"{\r\n"
			+ "    \"payload\": {\r\n"
			+ "        \"indentifier\": \"U\",\r\n"
			+ "        \"domainId\": \"KMBL173306\",\r\n"
			+ "        \"firstName\": \"act0507\",\r\n"
			+ "        \"middleName\": \"Tanya\",\r\n"
			+ "        \"lastName\": \"052\",\r\n"
			+ "        \"emailId\": \"Retest3380m@gmail.com\",\r\n"
			+ "        \"active\": \"N\",\r\n"
			+ "        \"positionType\": \"CMT Maker\",\r\n"
			+ "        \"territoryType\": \"National\",\r\n"
			+ "        \"functions\": \"New function\",\r\n"
			+ "        \"grade\": \"M21\",\r\n"
			+ "        \"locationCode\": \"H32\",\r\n"
			+ "        \"locationName\": \"DElhi\",\r\n"
			+ "        \"supervisorEmpCode\": \"ACT21\",\r\n"
			+ "        \"supervisorName\": \"ACT21\",\r\n"
			+ "        \"ccCode\": \"12345\",\r\n"
			+ "        \"ccName\": \"Marketing\",\r\n"
			+ "        \"lobCode\": \"0389\",\r\n"
			+ "        \"employeeCode\": \"uu990\"\r\n"
			+ "    },\r\n"
			+ "    \"additionalArgs\": {\r\n"
			+ "        \"referenceNumber\": \"103\",\r\n"
			+ "        \"clientIdentifier\": \"kotak\"\r\n"
			+ "    }\r\n"
			+ "}";
	}
}
